name: SteamGifts Bot

on:
  workflow_run:
    workflows: ["Build & Push Docker image (GHCR)"]  # nome do workflow que faz o push
    types:
      - completed  # só dispara quando o outro terminar

jobs:
  run-bot:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull latest image
        run: docker pull ghcr.io/jotanmiguel/steamgifs-autojoin:master

      - name: Run containers
        run: |
          docker compose up -d

      - name: Check logs
        run: docker compose logs -f steamgifts-bot
